# Generated by Django 4.0.4 on 2022-05-27 12:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField()),
            ],
        ),
    ]
