# Generated by Django 4.0.4 on 2022-05-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/%d'),
        ),
    ]
