# Generated by Django 4.0.4 on 2022-05-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_image',
        ),
    ]
